import {test,expect} from '@playwright/test'
test('写真から路線を選び、WebP画像と出典を確認できる',async({page,request})=>{
 await page.goto('/')
 await expect(page.locator('.map-canvas canvas')).toBeVisible()
 await page.waitForLoadState('networkidle')
 const image=page.locator('.route-card').first().locator('img')
 await expect(image).toHaveAttribute('src',/\/photos\/.+\.webp$/)
 await expect.poll(()=>image.evaluate((el:HTMLImageElement)=>el.naturalWidth)).toBeGreaterThan(0)
 const url=await image.getAttribute('src');const response=await request.get(url!)
 expect(response.headers()['content-type']).toContain('image/webp')
 await page.locator('.route-card').first().click()
 await expect(page.locator('.detail-hero img')).toBeVisible()
 await page.locator('.spot-card:not(.compact-spot)').first().click()
 await expect(page.locator('.spot-popup .photo-credit')).toBeVisible()
 await page.screenshot({path:'/private/tmp/bus-photo-popup.png'})
 await page.getByRole('button',{name:'観光地詳細を閉じる'}).click()
 await page.getByRole('button',{name:'路線を探す',exact:true}).click()
 await page.getByRole('button',{name:'車窓・名路線',exact:true}).click()
 await expect(page.locator('.route-card').first()).toBeVisible()
 await expect(page.locator('.route-card').first()).toContainText('乗って楽しむ')
})
