import {spotKind,spotPinSvg} from './spot-symbols'
import mapVersion from '../data/map-version.json'
import {useLocale,t,localeUrl,LanguageSwitcher,sourceTextNote} from '../i18n'
import {useEffect,useRef,useState} from 'react'
import type {BusRoute,Spot} from '../data/catalog'
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url'
import {Plus,Minus,Maximize,Layers,MapPin} from 'lucide-react'
export function BusMap({routes,selected,onSelect,onSpot,spot}:{routes:BusRoute[];selected?:BusRoute;onSelect:(id:string)=>void;onSpot:(spot:Spot)=>void;spot?:Spot}){
 const locale=useLocale();
 const container=useRef<HTMLDivElement>(null);const map=useRef<import('maplibre-gl').Map|null>(null);const callbacks=useRef({onSelect,onSpot,locale});callbacks.current={onSelect,onSpot,locale};const spotRequest=useRef(0);const activeSpot=useRef(spot?.id);activeSpot.current=spot?.id;const markerButtons=useRef<HTMLButtonElement[]>([]);const layoutMarkers=useRef<(()=>void)|null>(null);const [ready,setReady]=useState(false);const [error,setError]=useState(false);const [terrain,setTerrain]=useState(false)
 useEffect(()=>{setReady(false);let disposed=false;let instance:import('maplibre-gl').Map;void Promise.all([import('maplibre-gl'),import('pmtiles')]).then(([ml,pm])=>{if(disposed||!container.current)return;ml.setWorkerUrl(workerUrl);ml.addProtocol('pmtiles',new pm.Protocol().tile);instance=new ml.Map({container:container.current,style:'https://tiles.openfreemap.org/styles/positron',center:[136,36],zoom:4.4,attributionControl:{compact:true}});map.current=instance;instance.on('error',()=>setError(true));instance.on('load',async()=>{
 const pinImage=new Image();pinImage.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(spotPinSvg());await pinImage.decode();if(disposed)return;instance.addImage('tourism-place',pinImage);

 const tileUrl=import.meta.env.VITE_BUS_PMTILES_URL || new URL('/'+mapVersion.routeKey,window.location.origin).href
 instance.addSource('bus-routes',{type:'vector',url:`pmtiles://${tileUrl}`} )
 const sourceLayer={'source-layer':'bus_routes'}
 instance.addLayer({id:'bus-line',type:'line',source:'bus-routes',...sourceLayer,paint:{'line-color':['get','color'],'line-width':['interpolate',['linear'],['zoom'],5,1,12,3],'line-opacity':0.85}})
 instance.addLayer({id:'bus-hit',type:'line',source:'bus-routes',...sourceLayer,paint:{'line-width':22,'line-opacity':0}})
 instance.addSource('stops',{type:'geojson',data:{type:'FeatureCollection',features:[]}});instance.addLayer({id:'stop-dots',type:'circle',source:'stops',minzoom:9,paint:{'circle-radius':5,'circle-color':'#fff','circle-stroke-color':'#c36b43','circle-stroke-width':2}})
 instance.addSource('collected-spots',{type:'geojson',data:'/data/spot-points.geojson?v='+mapVersion.points,cluster:true,clusterRadius:36,clusterMaxZoom:11})
 instance.addLayer({id:'collected-spots',type:'symbol',source:'collected-spots',filter:['!', ['has','point_count']],minzoom:5,layout:{'icon-image':'tourism-place','icon-size':0.65,'icon-anchor':'bottom'}})
 instance.addLayer({id:'spot-clusters',type:'circle',source:'collected-spots',filter:['has','point_count'],paint:{'circle-color':'#c36b43','circle-radius':['step',['get','point_count'],16,20,20,100,25],'circle-stroke-color':'#fff','circle-stroke-width':2}})
 instance.addLayer({id:'cluster-count',type:'symbol',source:'collected-spots',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-font':['Noto Sans Regular'],'text-size':11},paint:{'text-color':'#fff'}})
 instance.addLayer({id:'spot-names',type:'symbol',source:'collected-spots',filter:['!', ['has','point_count']],minzoom:12,layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':11,'text-offset':[0,0.5],'text-anchor':'top'},paint:{'text-color':'#394e3d','text-halo-color':'#fff','text-halo-width':2}})
 instance.on('click','spot-clusters',async e=>{const feature=e.features?.[0];if(!feature||feature.geometry.type!=='Point')return;const source=instance.getSource('collected-spots') as import('maplibre-gl').GeoJSONSource;const zoom=await source.getClusterExpansionZoom(feature.properties.cluster_id);instance.easeTo({center:feature.geometry.coordinates as [number,number],zoom})})
  instance.on('click','collected-spots',async e=>{const feature=e.features?.[0];const p=feature?.properties;if(!p||feature.geometry.type!=='Point')return;const coordinate=feature.geometry.coordinates as [number,number];const request=++spotRequest.current;let detail:Spot={id:p.id,name:p.name,nameEn:p.nameEn,category:callbacks.current.locale==='en'?'Place':'観光地',description:callbacks.current.locale==='en'?'Details could not be loaded. Please check the source.':'詳細を取得できませんでした。場所の出典をご確認ください。',stop:t('最寄りバス停は調査中',callbacks.current.locale),walk:0,coordinate,photo:'',source:p.source,accessVerified:false,coordinateKind:p.coordinateKind,publisher:p.publisher};try{const response=await fetch(`/api/spots/${encodeURIComponent(p.id)}`);if(response.ok){const data=await response.json() as Spot;detail={...data,stop:data.stop||t('最寄りバス停は調査中',callbacks.current.locale)}}}catch{/* Keep source and coordinates usable when details cannot be fetched. */}if(!disposed&&request===spotRequest.current)callbacks.current.onSpot(detail)})
 instance.addSource('gsi',{type:'raster',tiles:['https://cyberjapandata.gsi.go.jp/xyz/std/{z}/{x}/{y}.png'],tileSize:256,attribution:'地図：国土地理院'});instance.addLayer({id:'gsi',type:'raster',source:'gsi',layout:{visibility:'none'}},'bus-line')
 instance.on('click','bus-hit',e=>{spotRequest.current++;const id=e.features?.[0]?.properties?.id;if(id)callbacks.current.onSelect(id)})
 instance.on('mouseenter','bus-hit',()=>{instance.getCanvas().style.cursor='pointer'});instance.on('mouseleave','bus-hit',()=>{instance.getCanvas().style.cursor=''})
 setReady(true);setError(false)
 });}).catch(()=>setError(true));return()=>{disposed=true;instance?.remove();map.current=null}},[])
 useEffect(()=>{const m=map.current;if(!m||!ready)return; m.setPaintProperty('bus-line','line-color',selected?['case',['==',['get','id'],selected.id],'#c36b43',['get','color']]:['get','color']); m.setPaintProperty('bus-line','line-width',selected?['case',['==',['get','id'],selected.id],6,2]:3);m.setPaintProperty('bus-line','line-opacity',selected?['case',['==',['get','id'],selected.id],1,0.3]:0.85);
 const source=m.getSource('stops') as import('maplibre-gl').GeoJSONSource;source.setData({type:'FeatureCollection',features:(selected?.stops??[]).map(s=>({type:'Feature',properties:{name:s.name},geometry:{type:'Point',coordinates:s.coordinate}}))})
 if(selected&&selected.stops.length){const points=selected.stops.map(s=>s.coordinate);m.fitBounds([[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1]))],[Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))]],{padding:Math.max(20,Math.min(80,Math.min(m.getContainer().clientWidth,m.getContainer().clientHeight)/5)),maxZoom:12,duration:900})}
 markerButtons.current=[];let update=()=>{};let active=true;let markers:import('maplibre-gl').Marker[]=[];void import('maplibre-gl').then((ml)=>{if(!active||map.current!==m)return;markers=(selected?.spots??[]).map((s)=>{const el=document.createElement('button');el.className=`spot-map-pin ${s.scenic?'scenic':''}`;el.innerHTML=spotPinSvg(spotKind(s));el.dataset.spotId=s.id;el.setAttribute('aria-pressed',String(activeSpot.current===s.id));const label=document.createElement('span');label.className='spot-pin-label';label.textContent=locale==='en'?(s.nameEn||s.name):s.name;el.appendChild(label);markerButtons.current.push(el);el.setAttribute('aria-label',locale==='en'?(s.nameEn||s.name):s.name);el.addEventListener('click',()=>{spotRequest.current++;callbacks.current.onSpot(s)});return new ml.Marker({element:el,anchor:'bottom'}).setLngLat(s.coordinate).addTo(m)});update=()=>{const visible:import('maplibre-gl').Point[]=[];const ordered=[...markers].sort((a,b)=>Number(b.getElement().dataset.spotId===activeSpot.current)-Number(a.getElement().dataset.spotId===activeSpot.current));for(const marker of ordered){const el=marker.getElement();const point=m.project(marker.getLngLat());const chosen=el.dataset.spotId===activeSpot.current;el.hidden=!chosen&&visible.some(other=>point.dist(other)<28);if(!el.hidden)visible.push(point)}};layoutMarkers.current=update;m.on('moveend',update);update()});return()=>{active=false;m.off('moveend',update);if(layoutMarkers.current===update)layoutMarkers.current=null;markers.forEach(x=>x.remove())}

 },[selected,ready,locale])
 useEffect(()=>{if(!ready||!container.current)return;const observer=new ResizeObserver(()=>map.current?.resize());observer.observe(container.current);return()=>observer.disconnect()},[ready])
 useEffect(()=>{if(ready)map.current?.setLayoutProperty('spot-names','text-field',locale==='en'?['case',['!=',['coalesce',['get','nameEn'],''],''],['get','nameEn'],['get','name']]:['get','name'])},[locale,ready])
 useEffect(()=>{if(ready)map.current?.setLayoutProperty('gsi','visibility',terrain?'visible':'none')},[terrain,ready])
 useEffect(()=>{layoutMarkers.current?.();for(const el of markerButtons.current)el.setAttribute('aria-pressed',String(el.dataset.spotId===spot?.id));if(!spot)spotRequest.current++;if(spot&&ready)map.current?.flyTo({center:spot.coordinate,zoom:13,duration:700})},[spot,ready])
 return <div className="map-area"><div ref={container} className="map-canvas" aria-label={t("全国の観光路線バスマップ",locale)}/>{!ready&&<div className="map-loading">{t(error?'地図を読み込めません。路線一覧からも旅を探せます。':'日本の地図を開いています…',locale)}</div>}<div className="map-note"><span className="live-dot"/> {t(selected?selected.stops.length?'選択した路線と立ち寄りスポット':'線形未取得・公式案内をご確認ください':'地図を拡大して、路線から旅を探す',locale)}</div><div className="map-controls"><button aria-label={t("拡大",locale)} onClick={()=>map.current?.zoomIn()}><Plus size={20}/></button><button aria-label={t("縮小",locale)} onClick={()=>map.current?.zoomOut()}><Minus size={20}/></button><button aria-label={t("全国へ戻る",locale)} onClick={()=>map.current?.flyTo({center:[136,36],zoom:4.4})}><Maximize size={18}/></button></div><button className="layer-switch" aria-pressed={terrain} onClick={()=>setTerrain(!terrain)}><Layers size={17}/>{t(terrain?'国土地理院':'標準地図',locale)}</button><div className="map-legend"><i/>{t("観光路線バス",locale)}<MapPin size={14}/>{t("立ち寄りスポット",locale)}</div></div>
}
