import { createServerFn } from '@tanstack/react-start'
import {loadRoute,currentRouteSql} from './server/repository'
import type { BusRoute,Spot } from './data/catalog'
async function database(){const {env}=await import('cloudflare:workers');return (env as unknown as {DB:D1Database}).DB}
type CatalogRow={document:string;spot_count:number;previews:string}
function parsePreview(row:CatalogRow):BusRoute{return {...JSON.parse(row.document),spotCount:row.spot_count,spots:(JSON.parse(row.previews) as string[]).map(s=>JSON.parse(s) as Spot)}}
const catalogSelect=`SELECT r.document, (SELECT COUNT(*) FROM route_spots rs JOIN spots s ON s.id=rs.spot_id WHERE rs.route_id=r.id AND json_extract(s.document,'$.photo')<>'') AS photo_count, (SELECT COUNT(*) FROM route_spots WHERE route_id=r.id) AS spot_count, (SELECT json_group_array(document) FROM (SELECT s.document FROM route_spots rs JOIN spots s ON s.id=rs.spot_id WHERE rs.route_id=r.id ORDER BY json_extract(s.document,'$.photo')<>'' DESC,rs.sequence LIMIT 3)) AS previews FROM routes r`
export const getCatalog=createServerFn({method:'GET'}).handler(async()=>{const db=await database();const result=await db.prepare(`${catalogSelect} WHERE r.active=1 AND ${currentRouteSql("r")} AND (EXISTS(SELECT 1 FROM route_spots WHERE route_id=r.id) OR json_extract(r.document,'$.featured')=1) ORDER BY photo_count DESC,json_extract(r.document,'$.featured')=1 DESC,spot_count DESC,r.id LIMIT 60`).all<CatalogRow>();return result.results.map(parsePreview)})
export const getRoute=createServerFn({method:'GET'}).validator((id:string)=>{if(typeof id!=='string'||id.length>200)throw new Error('Invalid route');return id}).handler(async({data:id})=>{
 return loadRoute(await database(),id)
})
export const searchRoutes=createServerFn({method:'GET'}).validator((input:{query:string;region:string;withSpots:boolean;featuredOnly?:boolean})=>{if(typeof input.query!=='string'||input.query.length>100||typeof input.region!=='string'||input.region.length>20)throw new Error('Invalid search');return input}).handler(async({data})=>{
 const db=await database();const q=`%${data.query.replace(/[\\%_]/g,'\\$&')}%`
 const result=await db.prepare(`${catalogSelect} WHERE r.active=1 AND ${currentRouteSql("r")} AND (EXISTS(SELECT 1 FROM route_spots WHERE route_id=r.id) OR json_extract(r.document,'$.featured')=1) AND (?=0 OR json_extract(r.document,'$.featured')=1) AND (?='全国' OR r.region=?) AND (?=0 OR EXISTS(SELECT 1 FROM route_spots rs JOIN spots s ON s.id=rs.spot_id WHERE rs.route_id=r.id AND json_extract(s.document,'$.photo')<>'')) AND (r.name LIKE ? ESCAPE '\\' OR json_extract(r.document,'$.nameEn') LIKE ? ESCAPE '\\' OR json_extract(r.document,'$.operatorEn') LIKE ? ESCAPE '\\' OR json_extract(r.document,'$.featuredNameEn') LIKE ? ESCAPE '\\' OR json_extract(r.document,'$.featuredName') LIKE ? ESCAPE '\\' OR json_extract(r.document,'$.operator') LIKE ? ESCAPE '\\' OR json_extract(r.document,'$.prefecture') LIKE ? ESCAPE '\\' OR EXISTS(SELECT 1 FROM route_spots rs JOIN spots s ON s.id=rs.spot_id WHERE rs.route_id=r.id AND (s.name LIKE ? ESCAPE '\\' OR json_extract(s.document,'$.nameEn') LIKE ? ESCAPE '\\'))) ORDER BY photo_count DESC,json_extract(r.document,'$.featured')=1 DESC,spot_count DESC,r.id LIMIT 60`).bind(data.featuredOnly?1:0,data.region,data.region,data.withSpots?1:0,q,q,q,q,q,q,q,q,q).all<CatalogRow>();return result.results.map(parsePreview)
})
